### ISSUE TITLE
wikia.exe -translate -lang pt

### ISSUE THREAD

**Issue by natanprog** [adrianojn/wikia#2]
```
C:\Portable\WikiaYgoPro>tree /F
Listagem de caminhos de pasta
O número de série do volume é 0000008E 380A:C7AD
C:.
    cards-pt.cdb
    cards.cdb
    cards.json
    config.json
    wikia.exe

Não existem subpastas


C:\Portable\WikiaYgoPro>wikia.exe -translate -lang pt
8456 cards

C:\Portable\WikiaYgoPro>
```

@adrianojn #1 após executar o comando wikia.exe -translate -lang pt não acontece nada(nenhuma mudança) .... Se eu entendi bem o funcionamento da ferramenta, ela deveria atualizar o cards-pt.cdb ?

**Comment by adrianojn** [comment]
Toda vez que yugioh.wikia.com atualizada a API o arquivo `config.json` precisa ser atualizado. Eu atualizei.

**Comment by natanprog** [comment]
Adriano Soares, muito obrigado pela ferramenta e pela ajuda! (agora foi xD)
